/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.charlware.taulang.ui;

import java.io.File;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.PrintStream;
import java.nio.file.Files;

/**
 *
 * @author charlvj
 */
public class TauEditorPane extends javax.swing.JPanel {

    private File file = null;
    private boolean saved = false;
    
    /**
     * Creates new form TauEditorPane
     */
    public TauEditorPane() {
        initComponents();
    }

    public boolean isSaved() {
        return saved;
    }
    
    public boolean isNew() {
        return !file.exists();
    }
    
    public File getFile() {
        return file;
    }
    
    public void setFile(File file) {
        this.file = file;
    }
    
    public void newFile() {
        saved = false;
        file = null;
    }
    
    public void openFile(File file) throws IOException {
        this.file = file;
        StringBuilder sb = new StringBuilder();
        Files.lines(file.toPath())
                .forEach(line -> sb.append(line).append("\n"));
        txContents.setText(sb.toString());
    }
    
    public void saveFile() throws FileNotFoundException {
        try(PrintStream stream = new PrintStream(file)) {
            stream.print(txContents.getText());
        }
    }
    
    public void saveFile(File file) throws FileNotFoundException {
        if(file != null) {
            this.file = file;
        }
        saveFile();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        txContents = new javax.swing.JTextArea();

        txContents.setColumns(20);
        txContents.setRows(5);
        jScrollPane1.setViewportView(txContents);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txContents;
    // End of variables declaration//GEN-END:variables
}
